insert into vehicle(name, status, surname) values('Vaqif', 'AVAILABLE', 'Polat')
insert into vehicle(name, status, surname) values('Vahid', 'AVAILABLE', 'Korkmaz')
insert into vehicle(name, status, surname) values('Ali', 'AVAILABLE', 'Kilic')
insert into vehicle(name, status, surname) values('Memmedeli', 'AVAILABLE', 'Kilic')
insert into vehicle(name, status, surname) values('Zefer', 'AVAILABLE', 'Kilic')

insert into cleaner(name, surname, status) values('Ali', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Gulnur', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Sebnem', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Seadet', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Nazli', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ali', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Medine', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ali', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Elnur', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Kerem', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Leyla', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ismet', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Behruz', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ali', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Sebine', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ulvira', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Gulsen', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Vusale', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Sevinc', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Vusal', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ismayil', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Gul', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ali', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Masal', 'Kirac', 'AVAILABLE')
insert into cleaner(name, surname, status) values('Ekrem', 'Kirac', 'AVAILABLE')


